baseURL = "https://patrickcking.com/"
languageCode = "en-us"
title = "Patrick C King"
publishdir = "../public/"
theme        = "hello-friend-ng"
paginate     = 10
relativeURLs = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle = "Patrick King"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Patrick King's Landing Page"
  keywords = "homepage, blog, patrickcking"
  images = [""]

[permalinks]
  blog = "/:year/:month/:title/"

[taxonomies]
    category = "blog"

[languages]
  [languages.en]
    title = "Patrick King"
    subtitle = "Patrick's Home"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

[params.logo]
  logoText = "cd /home/pking"
  logoHomeLink = "/"
  logoCursorColor    = "#41FF00"
  logoCursorAnimate  = "2s"


# And you can even create generic menu
[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog"
[[menu.main]]
  identifier = "contact"
  name       = "Contact"
  url        = "/contact"
[[menu.main]]
  identifier = "events"
  name       = "Events"
  url        = "/events"

 # Socials
[[params.social]]
  name = "github"
  url  = "https://github.com/mr-mustash"

[[params.social]]
  name = "keybase"
  url  = "https://keybase.io/king"
[[params.social]]
  name = "docker"
  url  = "https://hub.docker.com/u/mrmustash"
