baseURL = "https://patrickcking.com/"
languageCode = "en-us"
title = "Patrick C King"
publishdir = "../public/"
theme        = "hello-friend-ng"
paginate     = 10
relativeURLs = true

PygmentsCodeFences = true
PygmentsStyle = "solarized"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle = "Patrick King"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Patrick King's Landing Page"
  keywords = "homepage, blog, patrickcking"

  footerRight = "Made in Oregon"

[permalinks]
  blog = "/:year/:month/:title/"

[taxonomies]
    category = "blog"

[languages]
  [languages.en]
    title = "Patrick King"
    subtitle = "Patrick's Home"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params.logo]
  logoText = "cd /home/pking"
  logoHomeLink = "/"
  logoCursorColor    = "#41FF00"
  logoCursorAnimate  = "2s"


# And you can even create generic menu
[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts"
[[menu.main]]
  identifier = "contact"
  name       = "Contact"
  url        = "/contact"
#[[menu.main]]
#  identifier = "events"
#  name       = "Events"
#  url        = "/events"

 # Socials
[[params.social]]
  name = "github"
  url  = "https://github.com/mr-mustash"

[[params.social]]
  name = "keybase"
  url  = "https://keybase.io/king"
[[params.social]]
  name = "docker"
  url  = "https://hub.docker.com/u/mrmustash"
